### Numpy array and basics
learn about python with chai aur code

In [24]:
import numpy as np 

In [25]:
## Creating array from list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:\n",arr_1d)

arr_2d= np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)

1D array:
 [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list=[1,2,3]
print("Python list multiplied by 2:", py_list*2) #repeats the list elements two times
#its a very easy multiplication


np_array = np.array([1, 2, 3]) #elements wise multiplication
print("Numpy array multiplied by 2:", np_array * 2)  # Correct: Multiplies each element by 

import time
start = time.time() # Start time
pylist=[i*2 for i in range(1000000)]
print("\nList operation time:", time.time() - start)

start = time.time() # Start time
np_array = np.arange(1000000) * 2 # Numpy arange() operation :array of 1 million elements, each multiplied by 2
print("\nNumpy operation time:", time.time() - start) # Numpy is significantly faster for large arrays

Python list multiplied by 2: [1, 2, 3, 1, 2, 3]
Numpy array multiplied by 2: [2 4 6]

List operation time: 0.4205441474914551

Numpy operation time: 0.02500176429748535


### Creating array from scratch
Methods on matrices

In [41]:


zeros = np.zeros((4,4)) # Creating a 2D array of zeros
print("2D array of zeros:\n", zeros)

ones=np.ones((2,3)) # Creating a 2D array of ones
print("2D array of ones:\n", ones)

full=np.full((2,2), 7) # Creating a 2D array filled with a specific value of 2 by with value 7
print("2D array filled with 7:\n", full)

#most important
random = np.random.random((2,3)) # Creating a 2D array with random values (2 rows and 3 columns)
print("\nRandom 2D array:\n", random)

sequence=np.arange(0, 10, 2) # Creating a 1D array with a sequence of numbers from 0 to 10 with a step of 2
print("\n1D array with a sequence of numbers:\n", sequence)


2D array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
2D array filled with 7:
 [[7 7]
 [7 7]]

Random 2D array:
 [[0.08661328 0.60367266 0.11130731]
 [0.04525314 0.62099682 0.75263482]]

1D array with a sequence of numbers:
 [0 2 4 6 8]


## Vector,Matrices and Tensor